import { chromium } from "playwright";
const out = process.argv[2];
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 393, height: 852 } });
await page.goto("http://localhost:5173/", { waitUntil: "networkidle" });
await page.waitForTimeout(300);
await page.locator("nav button", { hasText: /^Shelf$/i }).first().click();
await page.waitForTimeout(300);
await page.screenshot({ path: out });
await browser.close();
